### ISSUE TITLE
How many samples per ray?

### ISSUE THREAD

**Issue by MultiPath** [sxyu/svox2#1]
Hi, thanks for sharing this amazing work. I tried to search how many samples you have used for each ray in the paper, however, I could not find anything related to that. I also checked your cuda kernel, and it seems that you have a dynamic number of samples on each ray. In that case, how do you pace along the ray? Could you confirm about that? Thank you so much!
![image](https://user-images.githubusercontent.com/5780274/145518584-de751f51-f22e-4faf-bc0f-b0183ceadaa5.png)

**Comment by sxyu** [comment]
Hi, in reality the number of samples is based on the voxel size. 
There is a config option called `step_size` which defaults to `0.5`. We simply take steps of this size along the ray until we exit the grid.
For example, if the voxel grid has resolution 512 and we are using the radius-1 ball bound for the inner scene, for example, there will be 512/0.5 = 1024 samples
