### ISSUE TITLE
What's the meaning of `ndc_coeff`?

### ISSUE THREAD

**Issue by wzy-99** [sxyu/svox2#100]
Hello, I don't understant the meaning of `ndc_coeff` in `LLFFDataset` and `tv_loss`. Can you give an explanation?

**Comment by sxyu** [comment]
ndc_coeff are just some conventient variables used for internal NDC computation.
```
self.ndc_coeffs = (2 * self.intrins_full.fx / self.w_full,
    2 * self.intrins_full.fy / self.h_full)
```

**Comment by sxyu** [comment]
I think tv loss refers to the total variation loss (not sure if that answers your question)

**Comment by wzy-99** [comment]
Thank you!
