### ISSUE TITLE
[BUG] New installation method for pytorch library

### ISSUE THREAD

**Issue by mzillag** [sxyu/svox2#107]
Currently, in enironment.yml file versions of pytorch and cudatoolkit is not defined. It caused a problem for colmap: "Error 803: system has unsupported display driver / cuda driver combination". This happens because in last versions installation command looks like this "conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia", so cudatoolkit installing with this package now - pytorch-cuda. I reinstalled pytorch with old command (conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch) and error is gone now.

**Comment by sxyu** [comment]
hello, I'm unsure why pytorch installation would impact COLMAP, but glad you were able to figure it out. CUDA installations with conda is always kind of easy to mess up

**Comment by mzillag** [comment]
It happens because we start proc_colmap.sh from conda environment, so .sh script use cudatoolkit from conda, as I see.
