### ISSUE TITLE
own image result bad

### ISSUE THREAD

**Issue by SSground** [sxyu/svox2#19]
When I use render_imgs_circle.py the result is poor, but the psnr value is high(PSNR:27).
I speculate that it is a problem of downsampling
If I modify the downsampling number to 8, what do I need to change
![image](https://user-images.githubusercontent.com/27821863/146521182-6078a8b9-ffeb-4c0f-87aa-36671343df01.png)

But use render_imgs.py the result is well

![image](https://user-images.githubusercontent.com/27821863/146521233-296ba045-679a-4db7-9b56-d412cc221cb2.png)

**Comment by SSground** [comment]
when I use to_svox1.py have a error
![image](https://user-images.githubusercontent.com/27821863/146523789-f5c5edd2-9892-4555-a76e-088e4fd0c57f.png)

**Comment by AndreaMas** [comment]
Not sure about the downsampling. However, you might want to render the scene from a bit further away. This can be done with the --radius parameter. Example: 
python render_imgs_circle.py <CHECKPOINT.npz> <data_dir> --radius=4.0

**Comment by Usama3059** [comment]
Hey, @SSground Can you please guide me how can I try this on custom images with RGB photos as a starting point?? secondly the output is mp4 video/render images,  can we extract the 3D model??

**Comment by SSground** [comment]
> 以 RGB 照片为起点的自定义图像上尝试这个吗？其次输出是 mp4 视频/渲染图像，我们可以提取 3D 模型吗？

Unable to extract mesh，And can you tell me where you went wrong so we can discuss
