### ISSUE TITLE
Negative density

### ISSUE THREAD

**Issue by limacv** [sxyu/svox2#20]
After training, I find that some voxels have negative density or zero density. I was wondering how the densities are defined if it's negative. Specifically, I find the negative density when I train using the default setting on the lego dataset.

**Comment by wtiandong** [comment]
> After training, I find that some voxels have negative density or zero density. I was wondering how the densities are defined if it's negative. Specifically, I find the negative density when I train using the default setting on the lego dataset.

I notice that negative density too. In my opinion, maybe during rendering/optimization, [sigma (density) below opt.sigma_thresh (opt.density_thresh) is ignored](https://github.com/sxyu/svox2/blob/59984d6c4fd3d713353bafdcb011646e64647cc7/svox2/csrc/render_lerp_kernel_cuvol.cu#L86).  The density itself is optimized without any constraints, so negative density doesn't mean anything because it's rectified.

**Comment by limacv** [comment]
邮件已送达 马力的邮箱

**Comment by universome** [comment]
@wtiandong Note that you refer to a density value after it was linearly interpolated from its surrounding voxel values. The negative density of a voxel still contributes (it just might be the case that its neighbours have high positive densities).

What I found more interesting is that if you manually clamp negative density values to 0 during training after each iteration — the training diverges! So, the model really needs negative densities to balance things out.

**Comment by limacv** [comment]
邮件已送达 马力的邮箱

**Comment by wtiandong** [comment]
> @wtiandong Note that you refer to a density value after it was linearly interpolated from its surrounding voxel values. The negative density of a voxel still contributes (it just might be the case that its neighbours have high positive densities).
> 
> What I found more interesting is that if you manually clamp negative density values to 0 during training after each iteration — the training diverges! So, the model really needs negative densities to balance things out.

That's interesting! 
Thank you for telling me!

**Comment by sxyu** [comment]
Hi, when rendering the density goes through a ReLU so it will always be positive. The negative voxel values allow it to have more general boundary shapes during interpolation.
