### ISSUE TITLE
Windows proc_colmap.sh can't find Colmap

### ISSUE THREAD

**Issue by trufty** [sxyu/svox2#27]
I noticed on windows that colmap was not being executed when running `bash proc_colmap.sh <img_dir>` leaving me with a folder of resized images and nothing else.  I do have it on my environment path.

Temporarily fixed the issue by adding the absolute path kike  `<path to colmap folder>/colmap.bat` everywhere the colmap command string is being built here: https://github.com/sxyu/svox2/blob/59984d6c4fd3d713353bafdcb011646e64647cc7/opt/scripts/run_colmap.py#L193

But I believe after some research that the correct windows command should be `colmap.bat  <commands>` and not `colmap <commands>` like in run_colmap.py. So try this first.

Hope it helps someone!

**Comment by sxyu** [comment]
We do not support Windows officially (have only tried on Linux). Thanks for the tip!
