### ISSUE TITLE
Fail to reproduce the results (bad visualization + low PSNR)

### ISSUE THREAD

**Issue by KelestZ** [sxyu/svox2#35]
Thanks for the amazing work. When I run the code on nerf_synthetic data (i.e., Lego), I couldn't get the same results as good as shown in the paper. I am showing a rendered LEGO result as below (right):
![0000](https://user-images.githubusercontent.com/27111467/147993191-2fb2b983-fdfd-495b-b6c2-0e3a779b8a44.png)
The PSNR I got is ~21 on lego. I believe I followed the instructions for the installation and running. The example command line is like: 
> python opt.py ../data/lego -t ckpt/lego -c configs/syn.json

I'm also repeating the experiments on other data. The Drum and the hotdog in Syn data and the fern in LLFF data seem fine. No idea about other data just yet. Some good examples I got:
![image](https://user-images.githubusercontent.com/27111467/147994335-4a10a13a-3581-4a2c-b696-69b70d724bfa.png)
![image](https://user-images.githubusercontent.com/27111467/147994311-50f929f7-c5f6-4a78-bd0a-6d86b6fb5191.png)
![image](https://user-images.githubusercontent.com/27111467/147994344-52e13ca5-853b-45c9-bf80-547b6c943924.png)

**Comment by pwais** [comment]
huh when i train lego from scratch i get good results:
![individualImage](https://user-images.githubusercontent.com/218145/147994236-64d551bc-68a0-4425-a0b0-4a8e75977330.png)
<img width="357" alt="Screen Shot 2022-01-03 at 4 24 31 PM" src="https://user-images.githubusercontent.com/218145/147994244-c2652223-47ee-4b95-b25d-ce66edca42c4.png">

you're using a pre-trained checkpoint?  maybe the code and checkpoint diverged

**Comment by KelestZ** [comment]
> you're using a pre-trained checkpoint? maybe the code and checkpoint diverged

No, I am training it from scratch. This seems werid when I got ok results on the other data..

**Comment by sarafridov** [comment]
Are you sure you're using the correct Lego data? The truck seems to be in a different position than it is in the standard NeRF-synthetic dataset; perhaps somehow multiple Lego training sets got intermixed?

**Comment by KelestZ** [comment]
> Are you sure you're using the correct Lego data? The truck seems to be in a different position than it is in the standard NeRF-synthetic dataset; perhaps somehow multiple Lego training sets got intermixed?

Thanks for the reminder. Fixed the issue and closed the question :)
