### ISSUE TITLE
CUDA 11 had already included the CUB

### ISSUE THREAD

**Issue by StarsTesla** [sxyu/svox2#37]
Hi there, when I tried to install the dependcies by following the README, the console gave a error that CUDA 11 had already included the CUB, and ask me to remove the incompatable CUB, so after I sudo apt-get uninstall the nvidiacub, the installation works.

If any one got the same problem should do some favor to you.

My env is :
cuda 11.3.1
3080ti

**Comment by sxyu** [comment]
Thanks for the recommendation. I think the README does say clearly that you should only install nvidiacub if the CUDA is below 11. Although I did just mess up this myself when setting up on a new computer :)
