### ISSUE TITLE
Beta loss is not canceled out in the case of early exit

### ISSUE THREAD

**Issue by podgorskiy** [sxyu/svox2#40]
In the early exit here: https://github.com/sxyu/svox2/blob/master/svox2/csrc/render_lerp_kernel_cuvol.cu#L259 , beta loss is not canceled out as in https://github.com/sxyu/svox2/blob/master/svox2/csrc/render_lerp_kernel_cuvol.cu#L375 ,  thus affecting the computation of gradients for background if the ray didn't hit anything.

Probably just easier to move the block at L259 before L252.

**Comment by sxyu** [comment]
I think you're right, thank you for the pointer to the bug

**Comment by sxyu** [comment]
It has been fixed in master now
