### ISSUE TITLE
'to_svox1.py'  not support the forward-facing scene ?

### ISSUE THREAD

**Issue by Spark001** [sxyu/svox2#63]
Thanks for your amazing work and code !

After I trained a voxel grid for forward-facing scene (LLFF style), I want to export the grid to plenoctree for rendering speedup. Therefore I found two assertions for the size of grid in the N3Tree, while my grid resolution is `[1408, 1156, 128]`.
```
1. assert grid.ndim == 4 and grid.shape[1] == D and grid.shape[2] == D, \
               "Grid must be a 4D array with first 3 dims equal"
2. assert (self.is_cubic_pow2)
```

When I called the `to_svox1.py` forcibly and use `volrend` to show the render result, I got uncorrect render result like the scene was squashed.

Your reply would be greatly appreciated.

**Comment by SSground** [comment]
I had the same problem and the whole thing was greyed out, do you have the same problem.
