### ISSUE TITLE
Help with the backward kernel trace_ray_cuvol_backward

### ISSUE THREAD

**Issue by amanshenoy** [sxyu/svox2#65]
Was just curious about how the backward kernel for trace_ray_cuvol was generated. Was the kernel generated through another application or were was the rendering function hand differentiated and implemented in the backward kernel? 

Any recommendations for how this backward kernel has to be implemented for an arbitrary rendering function?

**Comment by sarafridov** [comment]
This was hand-differentiated. To swap out the rendering function I think you'll need to either hand-differentiate it yourself and implement the kernel, or use a higher-level implementation with automatic differentiation (e.g. you can start with our JAX version linked from the readme, but note it is much slower and is feature-limited, recommended for experimentation but not for production).

**Comment by amanshenoy** [comment]
Will look into it! Thank you!
