### ISSUE TITLE
Compare to DirectVoxGO

### ISSUE THREAD

**Issue by BrianPugh** [sxyu/svox2#7]
I just noticed a new, fairly similar method to yours, [DirectVoxGo](https://github.com/sunset1995/DirectVoxGO). I was wondering if you could perform some comparisons/comments on their technique vs yours? Thanks!

**Comment by sxyu** [comment]
Hi Brian, thanks for the suggestion.
DirectVoxGo is an excellent work and I have been in contact with the author.
Actually the website https://alexyu.net/plenoxels/ contains a section on this work with some comments on the differences. 
Mainly (1) they are still using an MLP (2) they do not use any CUDA (only pure PyTorch) (3) they rely heavily on tightening the bounding box to get higher resolution (in our case, we simply sparsify the grid)

**Comment by BrianPugh** [comment]
thank you!

incase you haven't seen it, there's another paper "PERF: Performant, Explicit Radiance Fields" that doesn't use neural networks. The authors didn't release any code, but an interesting and relevant read

https://arxiv.org/pdf/2112.05598.pdf
