### ISSUE TITLE
csrc not load just with pycharm

### ISSUE THREAD

**Issue by LitterWindwind** [sxyu/svox2#73]
![image](https://user-images.githubusercontent.com/35981299/165670667-3f0f4777-8963-4fe8-94ce-da324b74e6b2.png)
![image](https://user-images.githubusercontent.com/35981299/165670706-54710da9-852d-49b8-b5fa-f66b2063e9fb.png)
![image](https://user-images.githubusercontent.com/35981299/165670745-1e84c733-aeb6-4c9d-8fef-a5922ec9254a.png)
I try this code on three different machines, only met error when I want to debug the code on PYCHARM, which is strange. The code and environment are totally same

**Comment by Immortal00ZJ** [comment]
Delete the folder svox2 after “pip install .”

**Comment by LitterWindwind** [comment]
It works！ Thanks

> Delete the folder svox2 after “pip install .”
