### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by RahulSinghalChicago** [sxyu/svox2#74]
Training on Colab Pro+ with 16GB GPU RAM and 54GB CPU, which should be enough for most models, but after a 6 epochs, the GPU runs out of memory.  I suspect it's a caching issue and not an absolute memory issue. Does anyone know how to clear GPU in between epochs?

**Comment by LiquidAmmonia** [comment]
I come accross the same issue. May I ask how did you solve this problem?
