### ISSUE TITLE
Should I set background_brightness to 0 if my custom images has black masked background?

### ISSUE THREAD

**Issue by dedoogong** [sxyu/svox2#76]
Hello~
I have took pictures of my test object and I manually masked(with black color) all background(like this https://www.piqsels.com/en/public-domain-photo-zudsj)
I have set background_brightness to 0 in custom.json and after training, I rendered with the result model and it shows "White" background and "Black" foggy cloud near the object. 

What parameter should I change to what value?
Please help me~
Thank you!

**Comment by Wuziyi616** [comment]
Hi @dedoogong I also have similar custom images. What's your final solution? Did you set it to 0?
