### ISSUE TITLE
Minimum samples? for using a custom image set (360)

### ISSUE THREAD

**Issue by dispoth** [sxyu/svox2#84]
Hi,

My objects are captured from an upper semi-sphere in relatively equally spaced elevations/azimuths and I have ~600 images per object. I'm interested in training on <100 images.

Will this produce quality renderings on novel (test) views?

What techniques, applicable to this codebase, are there for improving rendering quality (PSNR) with a low number of input samples?

Thanks!

**Comment by sarafridov** [comment]
The main results in the paper use the NeRF-synthetic dataset which has 100 training views and produces good results on new/test views. We also include an ablation study with 25 training views, where the trick for retaining reasonably good test results is to increase the weight on the TV regularization.
