### ISSUE TITLE
LLFF scene visualization

### ISSUE THREAD

**Issue by dogyoonlee** [sxyu/svox2#90]
How to visualize the LLFF scene (forward-facing scene) like the other nerf-like visualization?

I tried to modify the scale factor, render radius, and the other factors similar to nerf-code, but it did not work well.
Specifically, I guess there are some problems on render poses for spiral view.

Here are my visualization sample for forward-facing scene, which is formatted like LLFF dataset

![image](https://user-images.githubusercontent.com/62277785/187877858-19b78602-03b7-412a-967c-d2a4292a7903.png)

visualization of previous nerf-based code is as follows

![image](https://user-images.githubusercontent.com/62277785/187877948-b6170a70-bcd2-4e10-855f-cbb70bbb9f50.png)

**Comment by dogyoonlee** [comment]
solved.

ndc_coeffs for svox2.Camera was the problem.

**Comment by cwchenwang** [comment]
> solved.
> 
> ndc_coeffs for svox2.Camera was the problem.

how to change the ndc_coeffs, I found ndc conversion in this repo is different from the NeRF

**Comment by povolann** [comment]
> solved.
> 
> ndc_coeffs for svox2.Camera was the problem.

Could you please share your solution? Thank you!

**Comment by xyIsHere** [comment]
> > solved.
> > ndc_coeffs for svox2.Camera was the problem.
> 
> Could you please share your solution? Thank you!

I solved this problem by adding ''--render_path'' argument in the command, e.g.,
python render_imgs.py ./ckpt/fern_exp/ckpt.npz ./data_dir/nerf_llff_data/fern/ --no_imsave --render_path
